### ISSUE TITLE
Text Loader Uses Deprecated Encoding Method

### ISSUE THREAD

**Issue by samimak37** [dhmit/gender_analysis#115]
In `common.py` it appears like we're using a deprecated encoding method when we're trying to load documents from files:
https://github.com/dhmit/gender_analysis/blob/361e06244b40a1251130a4c9b5906b4386406fac/gender_analysis/common.py#L237

(Specifically, `codecs` is saying that the `U` encoding method is no longer supported)

We should take a look at this and see if there's a better/preferred encoding that we can use so that we don't have warnings showing up.

**Comment by shingkid** [comment]
Hi! Cool project, would like to work on some of the issues labeled `good first issue`.

According to the [codecs library documentation](https://docs.python.org/3/library/codecs.html),
> the builtin open() and the associated io module are the recommended approach for working with encoded text files

For the [built-in `open()`](https://docs.python.org/3/library/functions.html#open),
> an additional mode character permitted, 'U', which no longer has any effect, and is considered deprecated. It previously enabled universal newlines in text mode, which became the default behaviour in Python 3.0.

From what I can tell, this project is in Python 3.6 and above, and works mostly with encoded text files and not binary files. So I think a simple solution would be to use the built-in `open()` and do away with the redundant `U` mode. Feel free to correct me if I'm wrong :)

**Comment by samimak37** [comment]
Awesome! Thank you so much for wanting to contribute!

It looks like you're totally right! We're working with Python 3.8 for this project, so I don't see any reason to keep the operator around. Thank you for catching this!

**Comment by shingkid** [comment]
Happy to contribute! It's so rare to find projects that try to build tools specifically for the humanities :)

I'll go ahead and make the change, then create a pull request.
