### ISSUE TITLE
Clarify helper functions in `gender_adjective.py`

### ISSUE THREAD

**Issue by samimak37** [dhmit/gender_analysis#118]
It looks like there are a few different functions in `gender_adjective.py` (such as [this one](https://github.com/dhmit/gender_analysis/blob/ee1d41f1201202b9f608de8030c0059f0047d980/gender_analysis/analysis/gender_adjective.py#L154)) that appear to just be helper code for other functions in the file. Do we want these to be user-facing, or should we keep them as internal functions?

In the event that we want them user facing, we should go through and clarify the documentation and/or signatures of a lot of these, as some have ambiguous or confusing naming schemes (consider [`merge`](https://github.com/dhmit/gender_analysis/blob/ee1d41f1201202b9f608de8030c0059f0047d980/gender_analysis/analysis/gender_adjective.py#L154) vs [`merge_raw_results`](https://github.com/dhmit/gender_analysis/blob/ee1d41f1201202b9f608de8030c0059f0047d980/gender_analysis/analysis/gender_adjective.py#L178))

**Comment by MBJean** [comment]
This issue is resolved in the new `proximity` module (PR #159).
