### ISSUE TITLE
Give `PronounSeries` subject/object fields

### ISSUE THREAD

**Issue by samimak37** [dhmit/gender_analysis#132]
For some analysis functions, it would be helpful/necessary for the `PronounSeries` class to have subject/object distinctions for its pronouns. These will probably need to be optional parameters passed into its constructor

**Comment by ryaanahmed** [comment]
Good thought. Maybe also singular / plural?

> These will probably need to be optional parameters passed into its constructor

My gut instinct is that we should refactor PronounSeries so that these are individual attrs of the class and are mandatory. (Mandatory because so much of what we're doing in this package involves parts of speech.)

**Comment by ryaanahmed** [comment]
But let's find out if this is necessary as we're doing the work of porting each analytic function over.

**Comment by samimak37** [comment]
It looks like in `instance_distance.py` we're using the object/subject pronouns to do some analysis on the frequency of those pronouns between genders, but that's the only place I've found it (so far)

**Comment by kenalba** [comment]
None of this shows up in `gender_adjective.py` as far as I can tell.
