### ISSUE TITLE
Memoize tokenization and pos tagging within the `Document` class.

### ISSUE THREAD

**Issue by kenalba** [dhmit/gender_analysis#135]
Tokenization and parts-of-speech tagging is some of the most resource-intensive stuff we do, and there are several functions (like run_adj_analysis) where we do this multiple times to the same document. Memoizing this information once it's been computed within the `Document` function should provide substantial performance improvements with little overhead.

**Comment by kenalba** [comment]
I noticed while trying to throw a version of this together that we currently do two kinds of tokenization - a fast and dirty kind, with `get_tokenized_text`, that messes up in some places, and `nltk.word_tokenize`, which we use for more sophisticated analysis (namely, pos tagging). It'd be good to know the logic here - if it's purely a performance issue, that's fine, but it seems to me like we'd be wise to move everything over to word_tokenize for more reliable results. It'd also make memoization neater.

**Comment by kenalba** [comment]
PR #147 is a temporary fix on this problem, but actually addressing the issue I pointed to in my second comment is a larger issue that we'll need to figure out. I'll be thinking about this over the next week!

**Comment by MBJean** [comment]
Closing in favor of #170.
