### ISSUE TITLE
Corpus Creation Quickstart Guide

### ISSUE THREAD

**Issue by kenalba** [dhmit/gender_analysis#138]
We're already working on a quick start guide for the analysis functions of the toolkit, but that only works if the user uses our preselected corpus. The corpus quickstart guide will walk a user through creating a corpus, from listing some common places to find documents to creating a well-formed .csv file.

**Comment by MBJean** [comment]
Great suggestion! We've begun implementing this in #156 and will continue working up improvements to our documentation in the summer. Closing in favor or #170.
