### ISSUE TITLE
Create Smaller Test Corpus

### ISSUE THREAD

**Issue by samimak37** [dhmit/gender_analysis#144]
The small test corpus that we have right now is limited to a handful of novels, but these are still a little bit unwieldy for performing tests that can be checked by hand. We should try to create a corpus of documents that we can perform some meaningful tests with that we can also hand-verify the answers for.

We could probably even just use the [document test files](https://github.com/dhmit/gender_analysis/tree/master/gender_analysis/testing/test_data/document_test_files), as those are already of a small enough scope that we can sanity check our code.

**Comment by MBJean** [comment]
Great suggestion! While this is not standardized across the package, for the most part we've begun relying on our document test files in our testing. Closing this issue.
