### ISSUE TITLE
Build public-facing documentation

### ISSUE THREAD

**Issue by ryaanahmed** [dhmit/gender_analysis#40]
We want, ideally, two things:
1. an easy-to-read user's guide / tutorial that walks a user through creating a simple project using our toolkit
2. comprehensive API documentation, probably automatically generated

We're going to use
- Sphinx (http://www.sphinx-doc.org/en/master/) to automatically generate docs from our code
- Read the Docs for hosting our documentation https://readthedocs.org/

**Comment by ryaanahmed** [comment]
I'm not assigning this now, but I'd suggest that the test projects you're creating this week can feed into the user's guide.

I'll do the initial Sphinx setup.

**Comment by ryaanahmed** [comment]
Outline doc for the user's guide:
https://docs.google.com/document/d/1JXodqJZNiI76qbNnJhujHc4C8IN4V43S0xnZkm7vsk0/edit?ts=5d1b754e

**Comment by ryaanahmed** [comment]
Some good examples:
http://web.mit.edu/music21/doc/usersGuide/usersGuide_01_installing.html
https://guide.elm-lang.org/

**Comment by ryaanahmed** [comment]
https://gender-analysis.readthedocs.io/

**Comment by ryaanahmed** [comment]
@samimak37  --  Sphinx has a bunch of warnings that explain why some of the formatting is funky. You can install Sphinx into your venv with pip, and then go to `documentation/source` and run `make html` locally.

**Comment by ryaanahmed** [comment]
Let's add 'next' and 'previous' to the bottom of pages on the user's guide (i.e., so that users on the "Installation" page can click through to "tutorial" etc.)

**Comment by MBJean** [comment]
This issue is concluded as of PR #154. Closing.
