### ISSUE TITLE
Make gutenberg_loader work

### ISSUE THREAD

**Issue by ryaanahmed** [dhmit/gender_analysis#41]
This is a _stretch goal_. I'd suggest we don't work on this at all until we've got the rest of the toolkit working really robustly.

Ideally what we'd provide with the `gutenberg_loader` module is a simple API for letting users download and corpus-i-fy the PG corpus. This has some issues attached because we can't serve the files in their fully formatted form, with the headers and footers chopped off. It's also a pretty long download / processing step, so we need to make sure that we provide suitable information about what's about to happen, and think hard about fallback cases where things error out during the download, etc.

Might be cool for this to be an interactive mode thing.

**Comment by ryaanahmed** [comment]
Just deleted this stuff from master, per our decision not to get this done before initial release (#74). 

a2d7282cd2d26543f7de001931413929436a6f3b is the last commit that has these files. When we're ready to reintegrate with the project, checkout the following files from this commit:
```
gender_analysis/gutenberg_loader.py
gender_analysis/pywikibot.lwp
gender_analysis/user-config.py
```

**Comment by MBJean** [comment]
Closing this in favor of #170. This may be a useful goal for the summer, and so we can reference this issue as needed.
