### ISSUE TITLE
Implement a 'smart search' for metadata csv files

### ISSUE THREAD

**Issue by samimak37** [dhmit/gender_analysis#47]
This is something that is purely a convenience feature and not at all necessary for release, but might be a cool thing to add in the future.

A lot of times, a metadata csv file is stored in the same directory as the txt files that it references. It might be handy to enable Corpus to check if such a csv file exists and then use it if not supplied with a direct file path.

**Comment by ryaanahmed** [comment]
Cool idea -- but I'm going to call this a no-op. This creates ambiguity and a bit of added complexity for not a huge convenience win for the user. I'd rather be explicit. e.g., what if the user wants to load all the text files, but not the metadata -- do we require them to remove the csv in this situation?
