### ISSUE TITLE
Factor out anything project gutenberg specific

### ISSUE THREAD

**Issue by ryaanahmed** [dhmit/gender_analysis#6]
Since we want this toolkit to be dataset agnostic, we need to take anything that assumes you're working on Project Gutenberg and factor it out into a single module that _allows_ researchers to download and use PG as their dataset if they want, but doesn't have that assumption built into the whole project.

**Comment by ryaanahmed** [comment]
@samimak37 -- assigning this to you as it mostly affects the corpus module at first. Let's factor everything out into `corpus_gen` (which I think you've now renamed `gutenberg_loader`). Once @meesuekim's PR https://github.com/dhmit/gender_analysis/pull/15 is merged, you can start pulling bits out of the `document` module as well.

**Comment by ryaanahmed** [comment]
I think this is done! @samimak37, sanity check me?

**Comment by samimak37** [comment]
I think we've got it!

**Comment by ryaanahmed** [comment]
awesome. done.
