### ISSUE TITLE
Subject/object frequencies deletes text of last document in corpus

### ISSUE THREAD

**Issue by samimak37** [dhmit/gender_analysis#98]
The`subject_pronouns_gender_comparison` and `subject_vs_object_pronoun_freqs` functions in `gender_frequency.py` appear to eliminate the text of the last document in the corpus (along with the word counters) and then not do anything with it.

We should look into this and see if there's any particular reason, or if this is an artifact that just never got removed.

https://github.com/dhmit/gender_analysis/blob/ea1a155c0d0bc79c2d1edb6a65035f97d1d6fc3b/gender_analysis/analysis/gender_frequency.py#L298-L299

https://github.com/dhmit/gender_analysis/blob/ea1a155c0d0bc79c2d1edb6a65035f97d1d6fc3b/gender_analysis/analysis/gender_frequency.py#L356-L357

**Comment by kenalba** [comment]
After discussion, we agreed that this was probably a vestigial couple of lines, so I've cut them! I submitted a pull request that fixes this [here](https://github.com/dhmit/gender_analysis/pull/107#partial-pull-merging). I guess we close the issue after the request gets accepted?
